// Enhanced data structures for CV and JD analysis
// Domain-driven type definitions organized by business domain

// Import all domain types for backward compatibility
import type {
  PersonalInfo,
  ContactInfo,
  ReferenceEntry,
  ExperienceEntry,
  VolunteerEntry,
  EducationEntry,
  LanguageEntry,
  SkillsData,
  CertificationEntry,
  ProjectEntry,
  AwardEntry,
  PublicationEntry,
  BenefitEntry,
  JDData,
  CVData,
  ValidationResult,
  ValidationIssue,
  DataSuggestion,
  CompletenessScore,
  QualityScore,
  MissingDataAnalysis,
  ProcessingPipeline,
  DocumentCompatibility,
  SkillMatch,
  ExperienceMatch,
  EducationMatch,
  CompatibilityRecommendation,
  // Enums
  EmploymentType,
  ExperienceLevel,
  RemoteOption,
  EducationLevel,
  LanguageProficiency,
  BenefitCategory,
  ValidationCategory,
  SuggestionCategory,
  SuggestionSource,
  MissingFieldCategory,
  // Requirements and other interfaces
  JDRequirements,
  ExperienceRequirement,
  EducationRequirement,
  SalaryRange,
  PriorityAction,
  MissingField,
  ProcessingError,
  ProcessingStage
} from '../../types';

// Re-export for existing code compatibility
export type {
  PersonalInfo,
  ContactInfo,
  ReferenceEntry,
  ExperienceEntry,
  VolunteerEntry,
  EducationEntry,
  LanguageEntry,
  SkillsData,
  CertificationEntry,
  ProjectEntry,
  AwardEntry,
  PublicationEntry,
  BenefitEntry,
  JDData,
  CVData,
  ValidationResult,
  ValidationIssue,
  DataSuggestion,
  CompletenessScore,
  QualityScore,
  MissingDataAnalysis,
  ProcessingPipeline,
  DocumentCompatibility,
  SkillMatch,
  ExperienceMatch,
  EducationMatch,
  CompatibilityRecommendation,
  EmploymentType,
  ExperienceLevel,
  RemoteOption,
  EducationLevel,
  LanguageProficiency,
  BenefitCategory,
  ValidationCategory,
  SuggestionCategory,
  SuggestionSource,
  MissingFieldCategory,
  JDRequirements,
  ExperienceRequirement,
  EducationRequirement,
  SalaryRange,
  PriorityAction,
  MissingField,
  ProcessingError,
  ProcessingStage
};